### PR TITLE
chore: add squash commit of code reformat to blame ignore list

### PR DESCRIPTION
**Pull request by xc2**
~~As #60 is squash merged as https://github.com/rspack-contrib/rspack-examples/commit/441ddba0dab5fa11c26a79a210e111b6aa4eb4bf, we need add the new commit to blame ignore list.~~

### CODE REVIEW

**Comment by xc2** [comment]
cc @chenjiahan

**Comment by chenjiahan** [comment]
The commit history of this example repo is not that important, maybe we can just remove the .git-blame-ignore-revs file 😄

**Comment by xc2** [comment]
> The commit history of this example repo is not that important, maybe we can just remove the .git-blame-ignore-revs file 😄

removed.

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
🚀

**Pull request merged**
